import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google"
 
import { cn } from "@/lib/utils"
import {Providers} from './providers'
import { Toaster } from "@/components/ui/toaster";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";
import Sidebar from "@/components/sidebar/Sidebar";
import { Card } from "@/components/ui/card";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "variable",
})

export const metadata: Metadata = {
  title: "HMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn(" dark min-h-screen font-sans antialiased", fontSans.variable)} >
            <Providers>
            <div className={`h-dvh w-dvw min-w-[1024px] p-2 `}>
                <ResizablePanelGroup direction="horizontal">
                <ResizablePanel defaultSize={25} minSize={25} maxSize={30} ><Sidebar/></ResizablePanel>
                <ResizableHandle withHandle/>
                <ResizablePanel defaultSize={75} minSize={70} maxSize={75}>
                  <Card className="h-full">{children}</Card>
                </ResizablePanel>
            </ResizablePanelGroup>
            </div>
            </Providers>
            <Toaster />
      </body>
    </html>
  );
}